version: "2"
services:
  admin_fpm:
    image: manaphp/php70:1.0
    volumes:
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/tmp:/var/www/html/tmp
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/fpm/:/var/log/php
      - ../../../ManaPHP:/var/www/html/vendor/manaphp/framework
    restart: always
  admin_nginx:
    image: nginx:1.13.3
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      - /data/volumes/${COMPOSE_PROJECT_NAME}/admin/nginx:/var/log/nginx
    entrypoint: /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - ${WEB_PORT}:80
    restart: always