language: php
php:
  - '7.0'
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.composer/cache
notifications:
  email:
    - manaphp@qq.com
script:
  - env
  - eval "$(ssh-agent -s)"
  - GHDKM=.travis/ghdkm_framework; openssl aes-256-cbc -K $encrypted_4c5432c77f74_key -iv $encrypted_4c5432c77f74_iv -in $GHDKM.enc -out $GHDKM -d; chmod 0400 $GHDKM; ssh-add $GHDKM
  - git config --local user.name "ManaPHP Mark"
  - git config --local user.email "manaphp@qq.com"
  - (cd build;sudo chmod a+x git-subsplit.sh;sudo cp git-subsplit.sh "$(git --exec-path)"/git-subsplit;sudo sh split.sh;)
  - chmod a+x .travis/*.sh
  - sleep 180
  - .travis/travis_trigger.sh manaphp/app-api
  - .travis/travis_trigger.sh manaphp/app-user
  - .travis/travis_trigger.sh manaphp/app-admin
  - .travis/travis_trigger.sh manaphp/app-cli
  - .travis/travis_trigger.sh manaphp/app-cron