version: "2"
services:
  php:
    image: manaphp/php-fpm:1.0
    volumes: 
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ${APP_CODE_DIR}:/var/www/html
      - ./php/conf/www.conf:/etc/php/7.0/fpm/pool.d/www.conf
      - ./php/docker-entrypoint.d:/docker-entrypoint.d
      - /data/volumes/${COMPOSE_PROJECT_NAME}/php/log:/var/log/php
    restart: always
  nginx:
    image: nginx:1.13.3
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ${APP_CODE_DIR}:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      #- /data/volumes/${COMPOSE_PROJECT_NAME}/nginx/log:/var/log/nginx
    entrypoint: /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - ${WEB_PORT}:80
    restart: always