version: "2"
services:
  websocket:
    image: manaphp/php72:1.3
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/websocket/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/websocket/tmp:/var/www/html/tmp
      - ../../../ManaPHP:/var/www/html/vendor/manaphp/framework
    command: php -d opcache.enable_cli=on /var/www/html/public/index.php
    ports:
      - ${WS_PORT}:8300
    restart: always
