version: "2"
services:
  nginx:
    image: nginx:1.13.3
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ${ROOT_DIR}:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      #- /data/volumes/${COMPOSE_PROJECT_NAME}/nginx/log:/var/log/nginx
    entrypoint: /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - ${WEB_PORT}:80
    restart: always
  phpfpm:
    image: manaphp/php-fpm:1.0
    volumes: 
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ${ROOT_DIR}:/var/www/html
      - ./phpfpm/conf/www.conf:/etc/php/7.0/fpm/pool.d/www.conf
      - ./phpfpm/docker-entrypoint.d:/docker-entrypoint.d
      - /data/volumes/${COMPOSE_PROJECT_NAME}/phpfpm/log:/var/log/php
      - ${ROOT_DIR}/../../ManaPHP:/var/www/html/vendor/manaphp/framework:ro
    restart: always