version: "2"
services:
  swoole:
    image: manaphp/php70:1.0
    volumes: 
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - ../../../ManaPHP:/var/www/html/vendor/manaphp/framework
    command: php /var/www/html/swoole.php
    ports:
      - 9501:9501
    restart: always